wandb_version: 1

bidirectional:
  value: false
cell_type:
  value: LSTM
dropout:
  value: 0.2
embedding_size:
  value: 256
epochs:
  value: 10
hidden_layer_size:
  value: 256
learning_rate:
  value: 0.001
num_layers:
  value: 4
