wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1684323230.070486
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.8.10
      5: 0.14.0
      8:
      - 1
      - 5
bidirectional:
  desc: null
  value: false
cell_type:
  desc: null
  value: LSTM
dropout:
  desc: null
  value: 0.2
dropout_prob:
  desc: null
  value: 0.1
embedding_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 10
hidden_layer_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.001
num_layers:
  desc: null
  value: 2
