wandb_version: 1

bidirectional:
  value: true
cell_type:
  value: GRU
dropout:
  value: 0.1
embedding_size:
  value: 256
epochs:
  value: 10
hidden_layer_size:
  value: 128
learning_rate:
  value: 0.001
num_layers:
  value: 3
