wandb_version: 1

bidirectional:
  value: false
cell_type:
  value: LSTM
dropout:
  value: 0.1
embedding_size:
  value: 128
epochs:
  value: 10
hidden_layer_size:
  value: 128
learning_rate:
  value: 0.001
num_layers:
  value: 3
